name: Report an Issue
description: Report an issue with the mod.
labels: ["type: bug", "status: awaiting review"]
body:
  - type: dropdown
    id: version
    attributes:
      label: What version are you seeing the problem on?
      options:
        - 1.16.5
        - 1.18(.1)
        - 1.18.2
        - 1.19.2
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: Provide the steps you took to have this issue
      placeholder: |
        1. First do this...
        2. Then this...
        3. Finally this happens...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: latest.log
      description: Please copy and paste the text from `latest.log` or a Pastebin link.
      render: shell
    validations:
      required: true
