blank_issues_enabled: false
contact_links:
  - name: Moonflower Discord
    url: https://www.moonflower.gg/discord
    about: Have a question? Need support? Have a minor issue? Join our Discord and ask for help!
